### PR TITLE
Changes required to support Ruby v3.0+

### PR DESCRIPTION
**Pull request by alexbaumhoer**
Makes the required changes to support Ruby 3.0+ and specifically to [support the separation of positional and keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

I also upgraded the dependency on `activemodel` to require a version >= 6.1 as that is the first version of Rails that recommends using Ruby 3.0.

Due to the additional 3 major version requirements on activemodel I'm also increasing the major version of this gem to 2.

### CODE REVIEW

**Comment by alexbaumhoer** [comment]
One note regarding tests: there is one failing test but AFAICT it was failing without any of these changes. I'm happy to remove the assertion if others think that best.

```
  1) URL validation with no_local should not allow https://127.0.0.1.xip.io
     Failure/Error: expect(@user).not_to be_valid
       expected `#<UserWithNoLocal:0x0000000120ce18c0 @homepage="https://127.0.0.1.xip.io", @validation_context=nil, @errors=#<ActiveModel::Errors []>>.valid?` to return false, got true
     # ./spec/validate_url_spec.rb:173:in `block (4 levels) in <top (required)>'
```

**Comment by carlwiedemann** [comment]
> I also upgraded the dependency on activemodel to require a version >= 6.1 as that is the first version of Rails that recommends using Ruby 3.0.

Unfortunately, we can't make the change to ActiveModel 6.x because this gem is used by the Monolith, and Monolith is still using ActiveModel 5.2, and will need to do that until for the forseeable future.

The Ruby 2.7 monolith upgrade effort is currently focused on getting ActiveModel/ActiveRecord/ActiveSupport to 6.1, but there are some remaining core dependencies, the most significant being moving from Mongoid 6.4 to 7.5, which we are working on now. (Esoteric details [available here](https://checkr.atlassian.net/wiki/spaces/RD/pages/1820328111/Monolith+Ruby+2.7+Upgrade)). 

Double-splat is compatible with Ruby 2.6 (which Monolith is currently using), so that change should be fine, and I think we could bump the patch version. But I'd recommend holding off on any other dependencies in the meantime.

Let me know if you have any questions/concerns!

**Comment by alexbaumhoer** [comment]
@carlwiedemann thanks for the review! My thoughts:
- Could we not just lock the monolith to use the current version of this gem (1.2.0) and not upgrade it until the monolith has proper ActiveModel support?
- I could also get just upgrade ActiveModel* gems in the lockfile for this repository and not upgrade the dependencies as you suggest. The caveat with that would be if you tried to use this gem in a repository with ActiveModel < 6.1 and Ruby 3+ you are going to run into problems ... but not the worst thing in the world!
- Do you think it'd be a good idea to specify a Ruby version (in the Gemspec and as a `.ruby-version`). That might help alleviate some confusion for future travelers

**Comment by carlwiedemann** [comment]
> Could we not just lock the monolith to use the current version of this gem (1.2.0) and not upgrade it until the monolith has proper ActiveModel support?

Ah that didn't occur to me since the gem is source directly from Github rather than from Gemfury, which could host multiple versions. I did some reading of [Bundler docs](https://bundler.io/guides/git.html) and it seems that this could work if we create a proper tag.

All said, the Ruby 2.7 upgrade effort is planning to formally move all Github-hosted gems to Gitlab and Gemfury so that we don't risk any unexpected drift.

I'll discuss this with the other upgrade team members tomorrow and we'll develop a plan of action.

**Comment by alexbaumhoer** [comment]
After discussing with Carl I'm going to go ahead and close this PR

**Pull request closed without merging**
